export const CREATE_EVENT = 'createEvent'
export const DELETE_EVENT = 'deleteEvent'
export const DELETE_ALL_EVENT = 'deleteAllEvents'
export const ADD_LOG = 'addLog'
export const DELETE_ALL_LOGS = 'deleteAllLogs'
